name: Run Selenium Tests with ChromeDriver

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: remove to match Chrome version automatically
          chromedriver-version: '114.0.5735.90'
          chromeapp: google-chrome-stable

      - name: Start Xvfb (for GUI support)
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          chromedriver --url-base=/wd/hub &

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        if: always()
        env:
          URL_HOM: ${{ secrets.URL_HOM }}
        run: |
          mvn test -DENV=HMG-CLOUD -DBROWSER=CHROME_HEADLESS
