name: Run Tests

on:
  push:
  pull_request:
    branches:
      - master

  schedule:
    - cron: 0 12,20 * * 1-5

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | awk -F. '{print $1}' | awk '{print $NF}')

          wget -N https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          mv chromedriver-linux64/chromedriver .
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run tests e2e
        if: always()
        env:
          URL_HOM: ${{ secrets.URL_HOM }}
        run: |
          mvn test -DENV=HMG-CLOUD -DBROWSER=CHROME_HEADLESS