name: Pipe Selenium-Framework

on:
  pull_request:
    branches: [master]

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Runner tests with Chrome
        if: always()
        env:
          URL_HOM: ${{ secrets.URL_HOM }}
        run: mvn test -DENV=hmg-actions -DBROWSER=chrome-headless
