name: Run Selenium Tests with ChromeDriver

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Google Chrome (specific version)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
          sudo apt install ./google-chrome-stable_114.0.5735.90-1_amd64.deb

      - name: Set up ChromeDriver (specific version)
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '114.0.5735.90'
          chromeapp: google-chrome-stable

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        if: always()
        env:
          URL_HOM: ${{ secrets.URL_HOM }}
        run: |
          mvn test -DENV=HMG-CLOUD -DBROWSER=CHROME_HEADLESS