name: Run Selenium Tests with ChromeDriver

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromeapp: google-chrome-stable

      - name: Install Microsoft Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y wget software-properties-common
          wget https://packages.microsoft.com/keys/microsoft.asc -O- | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Set up EdgeDriver
        uses: nanasess/setup-edgedriver@v2
        with:
          edgeapp: microsoft-edge-stable

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        if: always()
        env:
          URL_HOM: ${{ secrets.URL_HOM }}
        run: |
          mvn test -DENV=HMG-CLOUD -DBROWSER=CHROME_HEADLESS