name: Tests E2E Selenium

on:
  push:
  pull_request:
    branches:
      - master

  schedule:
    - cron: 0 12,20 * * 1-5

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    env:
      URL_HOM: ${{ secrets.URL_HOM }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Install Chrome And ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
        
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget -N https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          mv chromedriver-linux64/chromedriver .
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Edge And EdgeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get install -y microsoft-edge-stable
        
          EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}')
          wget -N "https://msedgedriver.azureedge.net/${EDGE_VERSION}/edgedriver_linux64.zip"
        
          unzip -o edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/msedgedriver

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Tests Chrome
        if: always()
        run: mvn test -DENV=HMG-CLOUD -DBROWSER=CHROME_HEADLESS

      - name: Run Tests Edge
        if: always()
        run: mvn test -DENV=HMG-CLOUD -DBROWSER=EDGE_HEADLESS

      - name: Get Allure History
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Action From Marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history